export { default as Navbar } from "./Navbar";
export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as BlogTopic } from "./BlogTopic";
export { default as BlogTopicHowfx } from "./BlogTopic";
export { default as BlogTopicTwo } from "./BlogTopic";
export { default as BlogTopicForex } from "./BlogTopic";
export { default as BlogTopicStatagies } from "./BlogTopic";
export { default as Contact } from "./Contact";
// export { default as BlogTopicCareerWeb } from "./BlogTopic";
// export { default as BlogTopicCareerEdutech } from "./BlogTopic";
// export { default as FooterLink } from "./FooterLink";
